# Use the latest 2.1 version of CircleCI pipeline processing engine, see https:/welcome/circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm start 
  test:
    docker:
      - image: circleci/node:8.9-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test